### PR TITLE
When assigning a value to a superglobal, check for zval separation

### PR DESCRIPTION
**Pull request by steffengy**
This hopefully addresses the issue demonstrated in #725.

Not sure if that's the correct way to fix this, but it seemed relatively safe.

### CODE REVIEW

**Comment by steffengy** [comment]
@ovr 
Anything else I should change on this PR?

**Comment by ovr** [comment]
@steffengy 
I think this can be bugged when you will use

```zep
let _GET[12345] = "my test";
```

**Comment by steffengy** [comment]
@ovr
just like that it seems to work for me:
```
array(1) { [12345]=> string(7) "my test" }
```

Or do you mean a specific case, where it might bug?

**Comment by ovr** [comment]
@steffengy 
I mean this case, seems like okey

**Comment by ovr** [comment]
@phalcon @andresgutierrez Review it please

**Pull request merged**
