### PR TITLE
Implement global and namespace(d) function declaration

### PR DESCRIPTION
**Pull request by steffengy**
Addresses #517 
This is not intended to allow bypassing the OOP pattern, but to aid creating helper functions:
----

For example if you use PHP Code and want to define an 
language *helper* ```l($str)```
to return the localized version of a string.

This is  - for example - incredibly useful for the usage in templates.

- Sure you could also use a normal Method like ```App::l($str)```
which is really annoying to type every time.

- or workaround by using PHP to define something like
```function l($str) { return App::l($str); } ```

But a native implementation as addition to zephir's
useability is much **more comfortable**, because you can just declare the helper within
zephir.

### CODE REVIEW

**Comment by ovr** [comment]
Awesome :+1:

**Comment by steffengy** [comment]
@ovr 
what do you mean?
If you declare a function before the namespace declaration,
it will be declared as **global**.
If you declare it after the namespace declaration,
it will be declared **in said namespace**

I think the test cases I Added explain it pretty good: 
https://github.com/steffengy/zephir/blob/08ccaf120d2cdc0d5953b9d8788127615f0fbadc/test/fcall.zep#l7-17
https://github.com/steffengy/zephir/blob/08ccaf120d2cdc0d5953b9d8788127615f0fbadc/unit-tests/Extension/FcallTest.php#l56-57

**Comment by ovr** [comment]
@steffengy 
Thank for answer

**Comment by steffengy** [comment]
@ovr
No problem :)
Unfortunately, It will hopefully not take very much time to get this reviewed and (hopefully) merged.

**Comment by ovr** [comment]
@steffengy 

kk, I will review it ASAP

Will merge this with 
#765 
#751 
and release `0.6`

**Comment by steffengy** [comment]
@ovr 
Sounds good :)

**Comment by ovr** [comment]
Thank you

**Comment by mruz** [comment]
@steffengy can I add checking if global function with this name exist before?

**Comment by steffengy** [comment]
@mruz 
Yeah I think currently it only checks that per-file.
I think for a namespace/global scope it's still missing (should be somewhere in Compiler)

**Pull request merged**
