### PR TITLE
Removed sudo from json-c installer

### PR DESCRIPTION
**Pull request by SidRoberts**
Related to #1027.

### CODE REVIEW

**Comment by steffengy** [comment]
What is the reasoning behind this?

I cant really see the sense here, because you need the root permissions,
to install in /usr/local/lib/ , which is what this very likely tries to do.

The only reason it works for the travis parts is because they use a separate prefix,
to prevent this permission conflict.

**Comment by SidRoberts** [comment]
Phalcon no longer passes in Travis is due to [json-c not being installed properly](https://travis-ci.org/phalcon/cphalcon/jobs/71008323#L826) and the only thing I can think of is that Travis blocks `sudo` commands under the new infrastructure - meaning [`sudo make install`](https://github.com/phalcon/zephir/blob/master/install-json#L6) won't run.

Should we force people to run `sudo ./install-json` or create `./install-json-nosudo`?

**Comment by steffengy** [comment]
Json-C isn't the problem there, since it's installed to /home/travis/build/phalcon/cphalcon/build/lib/.

**Comment by SidRoberts** [comment]
It is the problem, see https://github.com/phalcon/cphalcon/pull/10667.

**Comment by steffengy** [comment]
It is not, the problem is simply that phalcon had the wrong lookup paths for libraries (as you also see due to the nature of the error message 
``parser.c:9:25: fatal error: json-c/json.h: No such file or directory``),
which is fixed by either setting the environment variables mentioned above or by doing the
fix applied: d6f25fcaef3d46c03ebf2a7ee4de2d2062286a16

It is fixed upstream (not the way I would fix it but fixed), as you can also see as phalcon's travis tests pass.

**Comment by SidRoberts** [comment]
Fair enough. :smile:

**Pull request closed without merging**
