### PR TITLE
Initial preparation for refactoring and moving forward

### PR DESCRIPTION
**Pull request by steffengy**
Changes:
- Template/Kernel files dependant on backend
- Active backend detection (PHP5->ZE2,PHP7->ZE3), 
- if no backend is specified via --backend ZendEngine2 for example
- Bare kernel for ZE3 and basic templates

This allows moving forward with PHP7 support,
because part by part implementation and refactoring
code generation in the process of it is made possible,
without breaking BC.

### CODE REVIEW

**Comment by steffengy** [comment]
ping @andresgutierrez 
Here you go, the PR you wanted.
the travis fail is due to a build timeout (>10 mins, whyever they seem to happen now...)

**Comment by steffengy** [comment]
@andresgutierrez 
Can you take a look at this?
It's a direct PR of what you wanted as such in #952

**Comment by andresgutierrez** [comment]
@steffengy Looking at this right now :)

**Comment by steffengy** [comment]
@andresgutierrez
Did you already take a look at it? :)

**Comment by andresgutierrez** [comment]
@steffengy Do you have more incoming changes?

**Comment by steffengy** [comment]
@andresgutierrez 
I am working on refactoring the parts required for PHP7 compatibility.

Basically introduce support feature by feature and refactoring part by part 
until 100% is reached, which is what I'm working on at a separate branch
( https://github.com/steffengy/zephir/tree/ng-refactor2 )

I think it makes sense to first merge this as a preparation.
This also isn't very dangerous in terms of BC.

Rolling in new changes as they are stable in regards of BC
(currently that other tree is failing compilation on 5.X, because it's very heavily in
development and in the progress stuff during that unfortunately sometimes breaks)
makes probably more sense and should be handled as a/multiple separate PRs.

**Comment by steffengy** [comment]
To clarify: 
That means no there won't be any more changes regarding that in **this PR**
and I would like this merged, if there isn't any problem.

**Comment by andresgutierrez** [comment]
Thanks!

**Pull request merged**
