### PR TITLE
Fix #905: Rework how and when (on unserialize) properties are initialized

### LINKED ISSUE #905: Object Member Variables Not Initialized During Unserialization [$10]
Hello,

Class member variables do not appear to correctly initialize when implementing the Serializable interface and unserializing an object.

```zephir
namespace Test;

class Test implements \Serializable {
	protected config = [1,2,3];

	public function serialize()
	{
		return serialize(this->config);
	}

	public function unserialize(var data)
	{
		// Should provide "[1,2,3]" but provides "null" instead.
		echo "Default class value for config: " . var_export(this->config, true) . "\n";
		let this->config = array_merge(this->config, unserialize(data));
	}
}
```

And a bit of PHP to create an object, serialize it and unserialize it, and print it out:

```php
<?php
$test = new \Test\Test();
$test2 = unserialize(serialize($test));
print_r($test2);
```

Running the PHP script generates:

```
Default class value for config: NULL
PHP Warning:  First argument is not an array in /home/bear/repos/zephir-synacor/Test.php on line 3
PHP Stack trace:
PHP   1. {main}() /home/bear/repos/zephir-synacor/Test.php:0
PHP   2. unserialize() /home/bear/repos/zephir-synacor/Test.php:3
Test\Test Object
(
    [config:protected] =>
)
```

Compare this to PHP's behavior:
```php
<?php
class Foo implements Serializable {
	protected $config = [1,2,3];
	public function serialize() {
		return serialize($this->config);
	}
	public function unserialize($data) {
		$this->config = array_merge($this->config, unserialize($data));
	}
}
$test = new Foo();
$test2 = unserialize(serialize($test));
print_r($test2);
```

Running this will result in:

```
Foo Object
(
    [config:protected] => Array
        (
            [0] => 1
            [1] => 2
            [2] => 3
            [3] => 1
            [4] => 2
            [5] => 3
        )

)
```

The config value is properly initialized and the array merge call works as expected.

Thanks Zephir folks!

<bountysource-plugin>
---
There is a **[$10 open bounty](https://www.bountysource.com/issues/11785632-object-member-variables-not-initialized-during-unserialization?utm_campaign=plugin&utm_content=tracker%2F280146&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F280146&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by steffengy**
Move the class property initialization logic to another internal function,
which is also used to initialize properties before unserialization.

### CODE REVIEW

**Comment by steffengy** [comment]
Until this there's still inconsistency on when a constructor is called, 
because if you have a constructor that echoes something and a child
class that uses a constructor to initialize it's properties it will nevertheless
also echo something without a ``parent::__construct`` being used in the
child's constructor.

This solution however doesn't call the parent constructor if the child does
not have a constructor and initializes properties,
that's not wanted behavior, right? (will look at fixing this soon, dont merge yet)

**Comment by steffengy** [comment]
@ovr @andresgutierrez 
Should be ready now, need a review on this.

**Comment by steffengy** [comment]
@andresgutierrez ping

**Comment by andresgutierrez** [comment]
Thanks

**Comment by mruz** [comment]
After this commit I receive:
```
var 0 string (49) "ErrorException[2]: First argument is not an array"
var 1 string (55) "/home/mruz/Dropbox/git/ice/base/app/Application.php[110]"
var 2 string (297) "Trace: 

#0 /home/mruz/Dropbox/git/ice/base/app/Application.php(96): Ice\Auth\Driver->__construct(Array)
#1 /home/mruz/Dropbox/git/ice/base/app/Application.php(59): App\Application->registerServices()
#2 /home/mruz/Dropbox/git/ice/base/public/index.php(30): App\Application->initialize()
```

I'm running [ice/base](https://github.com/ice/base) and in the [Application.php[110]](https://github.com/ice/base/blob/master/app/Application.php#L110) it create new auth model
[ice/auth/driver/model.zep](https://github.com/ice/framework/blob/dev/ice/auth/driver/model.zep#L22) which extends [ice/auth/driver.zep](https://github.com/ice/framework/blob/dev/ice/auth/driver.zep#L36)

**Comment by steffengy** [comment]
@mruz
Can you retry using https://github.com/phalcon/zephir/pull/1005 ?

**Comment by mruz** [comment]
@steffengy it seems that it works.

**Comment by mruz** [comment]
But:
```
var 0 string (80) "ErrorException[2]: array_fill_keys() expects parameter 1 to be array, null given"

#0 [internal function]: array_fill_keys(NULL, NULL)
#1 [internal function]: Ice\Mvc\Model->__construct(Array)
#2 [internal function]: Ice\Mvc\Model::findOne(Array)
#3 /app/modules/frontend/controllers/UserController.php(700): Ice\Auth\Driver\Model->login('user', 'user', false)
```

In the [ice/mvc/model.zep](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L52) `_fields` attribute should be an empty array.

**Comment by steffengy** [comment]
@mruz Can you retry again?

**Comment by mruz** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555b92710 in gc_remove_zval_from_buffer ()
(gdb) bt full
#0  0x0000555555b92710 in gc_remove_zval_from_buffer ()
No symbol table info available.
#1  0x0000555555b5ec98 in _zval_ptr_dtor ()
No symbol table info available.
#2  0x00007ffff0f32b5d in zephir_memory_restore_stack_common.4592.constprop () from /usr/lib64/php5/extensions/ice.so
No symbol table info available.
#3  0x00007ffff0f32c0d in zm_deactivate_ice () from /usr/lib64/php5/extensions/ice.so
No symbol table info available.
#4  0x0000555555b77854 in zend_deactivate_modules ()
No symbol table info available.
#5  0x0000555555b04c0d in php_request_shutdown ()
No symbol table info available.
#6  0x0000555555c2948a in ?? ()
No symbol table info available.
#7  0x00005555559bf29b in ?? ()
No symbol table info available.
#8  0x00007ffff648b8c5 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#9  0x00005555559bf339 in _start ()
No symbol table info available.
```

**Comment by steffengy** [comment]
that trace unfortunately is not very useful and propabably only indirectly related.

could you provide the generated c-sources/
(optimally) a test case that triggers said crash, since setting up and debugging
 ice framework takes a quite extensive amount of time.

**Comment by mruz** [comment]
I'm sending model's constructor:
```c
/**
 * Model constructor. Fetch Di and set it as a property.
 *
 * @param mixed filters
 * @param array data
 */
PHP_METHOD(Ice_Mvc_Model, __construct) {

        int ZEPHIR_LAST_CALL_STATUS;
        zephir_fcall_cache_entry *_0 = NULL, *_7 = NULL;
        zval *data = NULL;
        zval *filters = NULL, *data_param = NULL, *di = NULL, *_1 = NULL, *_2 = NULL, *_3 = NULL, *_4 = NULL, *_5, *_6 = NULL, *_8, *_9, *_10, *_11 = NULL;

        ZEPHIR_MM_GROW();
        zephir_fetch_params(1, 0, 2, &filters, &data_param);

        if (!filters) {
                filters = ZEPHIR_GLOBAL(global_null);
        }
        if (!data_param) {
                ZEPHIR_INIT_VAR(data);
                array_init(data);
        } else {
                zephir_get_arrval(data, data_param);
        }


        if (EG(called_scope) == ice_mvc_model_ce || EG(scope) == NULL) {
                zephir_init_properties(this_ptr TSRMLS_CC);
        }
        ZEPHIR_CALL_CE_STATIC(&di, ice_di_ce, "fetch", &_0, 8);
        zephir_check_call_status();
        zephir_update_property_this(this_ptr, SL("_di"), di TSRMLS_CC);
        ZEPHIR_INIT_VAR(_2);
        ZVAL_STRING(_2, "db", ZEPHIR_TEMP_PARAM_COPY);
        ZEPHIR_INIT_VAR(_3);
        ZVAL_NULL(_3);
        ZEPHIR_INIT_VAR(_4);
        ZVAL_BOOL(_4, 1);
        ZEPHIR_CALL_METHOD(&_1, di, "get", NULL, 0, _2, _3, _4);
        zephir_check_temp_parameter(_2);
        zephir_check_call_status();
        zephir_update_property_this(this_ptr, SL("_db"), _1 TSRMLS_CC);
        ZEPHIR_INIT_NVAR(_2);
        _5 = zephir_fetch_nproperty_this(this_ptr, SL("_fields"), PH_NOISY_CC);
        ZEPHIR_CALL_FUNCTION(&_6, "array_fill_keys", NULL, 107, _5, ZEPHIR_GLOBAL(global_null));
        zephir_check_call_status();
        zephir_fast_array_merge(_2, &(_6), &(data) TSRMLS_CC);
        ZEPHIR_CPY_WRT(data, _2);
        ZEPHIR_CALL_PARENT(NULL, ice_mvc_model_ce, this_ptr, "__construct", &_7, 6, data);
        zephir_check_call_status();
        _8 = zephir_fetch_nproperty_this(this_ptr, SL("_from"), PH_NOISY_CC);
        if (!(zephir_is_true(_8))) {
                ZEPHIR_INIT_NVAR(_3);
                ZEPHIR_INIT_NVAR(_4);
                zephir_get_class_ns(_4, this_ptr, 0 TSRMLS_CC);
                zephir_uncamelize(_3, _4);
                zephir_update_property_this(this_ptr, SL("_from"), _3 TSRMLS_CC);
        }
        _9 = zephir_fetch_nproperty_this(this_ptr, SL("_primary"), PH_NOISY_CC);
        if (!(zephir_is_true(_9))) {
                _10 = zephir_fetch_nproperty_this(this_ptr, SL("_db"), PH_NOISY_CC);
                ZEPHIR_CALL_METHOD(&_11, _10, "getid", NULL, 0);
                zephir_check_call_status();
                zephir_update_property_this(this_ptr, SL("_primary"), _11 TSRMLS_CC);
        }
        if ((zephir_method_exists_ex(this_ptr, SS("onconstruct") TSRMLS_CC) == SUCCESS)) {
                ZEPHIR_CALL_METHOD(NULL, this_ptr, "onconstruct", NULL, 0);
                zephir_check_call_status();
        }
        if (zephir_is_true(filters)) {
                ZEPHIR_CALL_METHOD(NULL, this_ptr, "loadone", NULL, 0, filters);
                zephir_check_call_status();
        }
        if ((zephir_method_exists_ex(this_ptr, SS("initialize") TSRMLS_CC) == SUCCESS)) {
                ZEPHIR_CALL_METHOD(NULL, this_ptr, "initialize", NULL, 0);
                zephir_check_call_status();
        }
        ZEPHIR_MM_RESTORE();

}
```

You can run ice framework and base. I can give you the steps. Also for me the trace is useless in this case.

**Comment by steffengy** [comment]
@mruz What are the steps required to trigger it?

**Comment by mruz** [comment]
```sh
#Install ice
composer create-project iceframework/framework
cd framework/vendor/phalcon/zephir
git fetch origin pull/1005/head:pr_1005
git checkout pr_1005
./install-json
./install
cd ../../../
./vendor/bin/zephir fullclean 
./vendor/bin/zephir build

#Add ice to php.ini and don't forget to restart your web server

#Get the ice/base
composer create-project iceframework/base --no-dev
cd base/

#Create db
mysql -u root -p
CREATE DATABASE demo_base CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT USAGE ON demo_base.* TO demo@localhost;
GRANT ALL ON demo_base.* TO demo@localhost IDENTIFIED BY 'demo';
flush privileges;
use demo_base;
source auth.sql;
quit;

#Prepare chmod
php private/index.php --handler=prepare --action=chmod

#Switch to root
su
#Run as webserver
sudo -u wwwrun gdb php
run public/index.php
bt full
```

**Comment by steffengy** [comment]
I'll probably need some time for this (potentially a few days), 
i have a idea what's going on but don't know why.


(The crash is triggered in DI::set (when given a closure), 
since somehow memory frames seem to get corrupted?)

**Comment by steffengy** [comment]
@mruz updated PR, please try again :)

**Comment by mruz** [comment]
Again looks like `_fields` attribute is not initialized before (it's array):
```
var 0 string (80) "ErrorException[2]: array_fill_keys() expects parameter 1 to be array, null given"
var 1 string (87) "/home/mruz/Dropbox/git/ice/base/app/modules/frontend/controllers/UserController.php[88]"
var 2 string (712) "Trace: 

#0 [internal function]: array_fill_keys(NULL, NULL)
#1 [internal function]: Ice\Mvc\Model->__construct()
#2 [internal function]: Ice\Auth\Driver\Model\Users->__construct(Array)
#3 [internal function]: Ice\Mvc\Model::findOne(Array)
#4 /home/mruz/Dropbox/git/ice/base/app/modules/frontend/controllers/UserController.php(88): Ice\Auth\Driver\Model->login('user', 'user', false)
#5 [internal function]: App\Modules\Frontend\Controllers\UserController->signinAction()
#6 [internal function]: Ice\Dispatcher->dispatch()
#7 /home/mruz/Dropbox/git/ice/base/app/Application.php(203): Ice\Mvc\App->handle(NULL, NULL)
#8 /home/mruz/Dropbox/git/ice/base/public/index.php(31): App\Application->handle()
#9 {main}
```

**Comment by steffengy** [comment]
@mruz Please try again using latest PR 
(fixed something else, eventually unrelated?), 
if it still fails please try a zephir fullclean and let me know

**Comment by mruz** [comment]
The same error with `array_fill_keys()` during user login, yes I ran `zephir fullclean`.

**Comment by steffengy** [comment]
This is strange, especially the stack trace:
```
#1 [internal function]: Ice\Mvc\Model->__construct()
#2 [internal function]: Ice\Auth\Driver\Model\Users->__construct(Array)
```

How is the child constructor called first... 
I'll probably have to take a look at this, when
I have more time, since it doesn't seem trivial at all and my tests
so far haven't showed similar bugs...

**Comment by steffengy** [comment]
@mruz 
Should be fixed now, can you confirm?

**Comment by mruz** [comment]
I have problem with [config/ini.zep](https://github.com/ice/framework/blob/dev/ice/config/ini.zep) constructor `_data` is empty
```
object(Ice\Config\Ini)#6 (1) {
  ["_data":protected]=>
  array(0) {
  }
}
```
http://pastebin.com/Sms4WDwY

**Comment by steffengy** [comment]
@mruz
Yeah my fault there, should also be fixed now.
Sorry to trouble you through all that :)
Please let me know if anything else fails.

**Comment by mruz** [comment]
I think [loadOne()](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L69) not work in the constructor, it should overwrite the `_data`, but there is empty array.

```c
/**
 * Model constructor. Fetch Di and set it as a property.
 *
 * @param mixed filters
 * @param array data
 */
PHP_METHOD(Ice_Mvc_Model, __construct) {

	int ZEPHIR_LAST_CALL_STATUS;
	zephir_fcall_cache_entry *_0 = NULL, *_7 = NULL;
	zval *data = NULL;
	zval *filters = NULL, *data_param = NULL, *di = NULL, *_1 = NULL, *_2 = NULL, *_3 = NULL, *_4 = NULL, *_5, *_6 = NULL, *_8, *_9, *_10, *_11 = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 0, 2, &filters, &data_param);

	if (!filters) {
		filters = ZEPHIR_GLOBAL(global_null);
	}
	if (!data_param) {
		ZEPHIR_INIT_VAR(data);
		array_init(data);
	} else {
		zephir_get_arrval(data, data_param);
	}


	if (EG(called_scope) == ice_mvc_model_ce) {
		zephir_init_properties(this_ptr TSRMLS_CC);
	}
	ZEPHIR_CALL_CE_STATIC(&di, ice_di_ce, "fetch", &_0, 8);
	zephir_check_call_status();
	zephir_update_property_this(this_ptr, SL("_di"), di TSRMLS_CC);
	ZEPHIR_INIT_VAR(_2);
	ZVAL_STRING(_2, "db", ZEPHIR_TEMP_PARAM_COPY);
	ZEPHIR_INIT_VAR(_3);
	ZVAL_NULL(_3);
	ZEPHIR_INIT_VAR(_4);
	ZVAL_BOOL(_4, 1);
	ZEPHIR_CALL_METHOD(&_1, di, "get", NULL, 0, _2, _3, _4);
	zephir_check_temp_parameter(_2);
	zephir_check_call_status();
	zephir_update_property_this(this_ptr, SL("_db"), _1 TSRMLS_CC);
	ZEPHIR_INIT_NVAR(_2);
	_5 = zephir_fetch_nproperty_this(this_ptr, SL("_fields"), PH_NOISY_CC);
	ZEPHIR_CALL_FUNCTION(&_6, "array_fill_keys", NULL, 105, _5, ZEPHIR_GLOBAL(global_null));
	zephir_check_call_status();
	zephir_fast_array_merge(_2, &(_6), &(data) TSRMLS_CC);
	ZEPHIR_CPY_WRT(data, _2);
	ZEPHIR_CALL_PARENT(NULL, ice_mvc_model_ce, this_ptr, "__construct", &_7, 6, data);
	zephir_check_call_status();
	_8 = zephir_fetch_nproperty_this(this_ptr, SL("_from"), PH_NOISY_CC);
	if (!(zephir_is_true(_8))) {
		ZEPHIR_INIT_NVAR(_3);
		ZEPHIR_INIT_NVAR(_4);
		zephir_get_class_ns(_4, this_ptr, 0 TSRMLS_CC);
		zephir_uncamelize(_3, _4);
		zephir_update_property_this(this_ptr, SL("_from"), _3 TSRMLS_CC);
	}
	_9 = zephir_fetch_nproperty_this(this_ptr, SL("_primary"), PH_NOISY_CC);
	if (!(zephir_is_true(_9))) {
		_10 = zephir_fetch_nproperty_this(this_ptr, SL("_db"), PH_NOISY_CC);
		ZEPHIR_CALL_METHOD(&_11, _10, "getid", NULL, 0);
		zephir_check_call_status();
		zephir_update_property_this(this_ptr, SL("_primary"), _11 TSRMLS_CC);
	}
	if ((zephir_method_exists_ex(this_ptr, SS("onconstruct") TSRMLS_CC) == SUCCESS)) {
		ZEPHIR_CALL_METHOD(NULL, this_ptr, "onconstruct", NULL, 0);
		zephir_check_call_status();
	}
	if (zephir_is_true(filters)) {
		ZEPHIR_CALL_METHOD(NULL, this_ptr, "loadone", NULL, 0, filters);
		zephir_check_call_status();
	}
	if ((zephir_method_exists_ex(this_ptr, SS("initialize") TSRMLS_CC) == SUCCESS)) {
		ZEPHIR_CALL_METHOD(NULL, this_ptr, "initialize", NULL, 0);
		zephir_check_call_status();
	}
	ZEPHIR_MM_RESTORE();

}
```

**Comment by steffengy** [comment]
@mruz
on what class is the constructor called, user?
I think the problem might be that it is called by a class which doesn't define a constructor
(-> auto generated parent zephir constructor call, doesnt pass params to parent constructor), 
which means that ```filters``` is probably null.
Can you confirm my theory?

**Comment by mruz** [comment]
Is called on [auth/driver/model/users.zep](https://github.com/ice/framework/blob/dev/ice/auth/driver/model/users.zep), eg.

```php
$user = new \Ice\Auth\Driver\Model\Users(["username" => 'user']);
// or
$user = \Ice\Auth\Driver\Model\Users::findOne(["username" => 'user']);
```

**Comment by steffengy** [comment]
@mruz
Thanks, it's exactly what I thought of. Will look into it asap

**Comment by steffengy** [comment]
@mruz Hopefully also fixed now

**Comment by mruz** [comment]
Not everything works:
```
var 0 string (80) "ErrorException[2]: array_fill_keys() expects parameter 1 to be array, null given"
var 1 string (84) "/app/modules/frontend/controllers/UserController.php[90]"
var 2 string (660) "Trace: 

#0 [internal function]: array_fill_keys(NULL, NULL)
#1 [internal function]: Ice\Mvc\Model->__construct('1', Array)
#2 [internal function]: Ice\Auth\Driver\Model\Users->__construct('1')
#3 /app/modules/frontend/controllers/UController.php(90): Ice\Mvc\Model::findOne('1')
#4 [internal function]: App\Modules\Frontend\Controllers\UserController->activationAction('1', '065ff0949c7403c28ff75960e242e62a')
```

In the 90 line 
```php
$user = App\Models\Users::findOne($id);
```

`App\Models\Users` extends `Ice\Auth\Driver\Model\Users`, but in the `#3` `Ice\Mvc\Model` is called first

**Comment by steffengy** [comment]
@mruz
```App\Models\Users``` is a PHP defined-class?
And the stacktrace order seems correct except 
that App\Models\Users::__construct should be called first, if existing?

**Comment by mruz** [comment]
> App\Models\Users is a PHP defined-class?

Yes

**Comment by steffengy** [comment]
Does that class define a constructor? (I guess no?)
Does that constructor call the parent explicitly?

**Comment by mruz** [comment]
Well you guessed, there is no constructor in the `App\Models\Users`.

**Comment by mruz** [comment]
Why in the trace step3 is `Ice\Mvc\Model::findOne('1')` instead of `App\Models\Users::findOne('1')`?

**Comment by steffengy** [comment]
because the method is inherited but still belongs to the "physical" parent class entry of Mvc\Model (since it was defined for that class), 
but is called with another scope (``App\Models\Users``). It is an internal function, therefore the different behavior.

**Comment by steffengy** [comment]
@mruz
Did some refactoring and changed how property initialization generally works to a
better solution (initialize propertys once at object initialization not in the constructor)
Can you check if that works for you?
Thanks for your testing :)

**Comment by mruz** [comment]
All my test pass, it seems it works now.
Thanks for fixing ;)

I will test #537 if working now.

**Comment by mruz** [comment]
I think "Can't overwrite the default array data if extends" issue sitll occurs, but I worked it out with this by `onConstruct()` and `setRules()`, [Users.php](https://github.com/ice/base/blob/master/app/common/models/Users.php#L59).

**Comment by steffengy** [comment]
@mruz 
Can't reproduce that using the example code in #537 (since that definitely works for me)

**Comment by mruz** [comment]
How about if extends in php scope?

```php
class PhpPublicPropertiesTest extends \Test\Properties\PublicProperties
{

    protected someGetterSetterArray = ['doly'];
}
```

```php
$test = new PhpPublicPropertiesTest();
var_dump($test->getSomeGetterSetterArray());
```

**Comment by steffengy** [comment]
@mruz 
Yea I will probably have to rework the whole initialization logic again (third time^^)
to match the exact PHP implementation (just found out now how php seems to do it)
Will update you, when I have the next implementation ready.

**Comment by hylent** [comment]
I guess object properties are initialized after `object_init` and before invoking `__contruct`

**Comment by steffengy** [comment]
@hylent
in php they are initiialized during object_init, 
in my implementation they will be initialized as you described it.

@mruz
Can you confirm whether this is now fixed in the latest state of the PR?

**Comment by mruz** [comment]
@steffengy yes this is fixed, I see #537 too. 
Thanks for your work and cooperation :)

**Pull request merged**
