### PR TITLE
Rebuild the Win32 Parser (VC2012) and remove unnecessary cygwin binaries

### PR DESCRIPTION
**Pull request by steffengy**
Also update json-c to newest revision and add build instructions.

Should address #824

### CODE REVIEW

**Comment by steffengy** [comment]
@ping ovr

**Comment by andresgutierrez** [comment]
Thanks

**Comment by BonnieDoug** [comment]
+1 will give it a go tonight :-)

**Comment by steffengy** [comment]
Yeah but the WINDOWS.md assumes that you use the already built parser.
(because building the parser is annoying)
The section about building the parser is just for information,
if you want to do it yourself.

**Comment by BonnieDoug** [comment]
Ah, I get it. Still learning the ropes here, think I've been a bit spoilt in the past with symfony holding your hand every step of the way (at the expense of speed). Just bought "head first : C" so hopefully I'll get a bit more adept and actually contribute rather than leeching :-)

**Comment by steffengy** [comment]
Yeah I admit that it's not very intuitive,
but I just added the instructions there quickly, 
that if somebody wanted to build it, he could, even though he wouldn't need to.

It should be definitely marked as optional with explanation,
that you could also just use the .exe from the repository :)

**Pull request merged**
