### PR TITLE
Use the current array, not the fetched one when updating properties

### PR DESCRIPTION
**Pull request by olivier-monaco**
Issue #743

### CODE REVIEW

**Comment by ovr** [comment]
@olivier-monaco 
Can you please added tests for it?

**Comment by olivier-monaco** [comment]
Hum hum, I will try... but for the moment, composer did not install phpunit (missing "phpunit/phpunit" in require-dev) and now:
<pre>
PHP Fatal error:  Class 'Test\Arithmetic' not found in /volumes/vg1-data/Web/vhosts/phalcon2/zephir/unit-tests/Extension/ArithmeticTest.php on line 28
</pre>

**Comment by olivier-monaco** [comment]
And now one test fails because of:
<pre>
PHP Fatal error:  Class 'Test\ExitDie' not found in /volumes/vg1-data/Web/vhosts/phalcon2/zephir/unit-tests/Extension/fixtures/exit.php on line 3
</pre>

**Comment by olivier-monaco** [comment]
I still have issue with Test\ExitDie but my tests works fine.

**Comment by ovr** [comment]
Thank you

**Pull request merged**
