### PR TITLE
[WIP] Initial PHP 7 compatibility

### PR DESCRIPTION
**Pull request by steffengy**
This PR provides only an "intermediate refactoring" of the current source code,
which is not the abstract state zephir would need to support PHP code generation,
with total separation of backends.

This PR does only aim to provide PHP7 compatibility and therefor required
some refactoring, which was done in a limited extent.

Stuff which would have to be done for that:
-
- Move the operator/statement/optimizer **logic that's depending on the backend** to 
classes of the backend (which currently partly is just in-place in the old files with conditionals)<br/>
So you would have a class providing the **general implementation**, which is **shared** between backends (common code for validating parameters, checking input, ...)
<br/>and a version per backend which handles **code generation** (and temp variable usage, ...)

This PR
====
- provides initial support for PHP7 (ZE3) Extensions (compiler and kernel support)<br/>
(testcases pass, **except preg-match**, requires proper reference support in zephir)

Todos before merge
===
- [ ] compare generated sources for ZE2 (zephir tests, if BC is still guaranteed)
- [ ] complete some backend definitions (in BaseBackend)
- [ ] general cleanup, eventually more performance tweaks/documentation

### CODE REVIEW

**Comment by fezfez** [comment]
Wow, great job :beers: !

**Comment by ovr** [comment]
@steffengy 
Good work :beer: :cake:

**Comment by steffengy** [comment]
@ovr 
There is much polishing and cleanup to do, as mentioned in the todos above also.
ultimatively all backend dependant code should be in the respective backend,
if it doesn't require complicating the codebase too much.

Generally this PR isn't quite ready yet, so reviewing does only make limited sense.

**Comment by ovr** [comment]
@steffengy 
stay calm, it's notice ;)

**Comment by Green-Cat** [comment]
:+1:

**Comment by steffengy** [comment]
@ovr
I just didn't want you to waste your time, but it's ofcourse appreciated :)

**Comment by andresgutierrez** [comment]
Thank you!, I think it's time to introduce a development branch?

**Comment by steffengy** [comment]
@andresgutierrez
Could make sense, yes, especially since there's still pretty much to do,
and this is nowhere near total stability for ZE2 (BC) and ZE3.

What do you propose?

**Comment by andresgutierrez** [comment]
I'm going to create a new branch, would you mind to submit your PR there?

**Comment by steffengy** [comment]
@andresgutierrez 
Sure, will have to resubmit it though https://github.com/isaacs/github/issues/18

**Comment by steffengy** [comment]
@andresgutierrez 
Against which branch do you want the PR to be? Just "development"?

**Comment by andresgutierrez** [comment]
@steffengy Could you please submit this against https://github.com/phalcon/zephir/tree/development ?

**Comment by steffengy** [comment]
@andresgutierrez Sure

**Pull request closed without merging**
