### PR TITLE
PHP7: Fix some bugs, generally add more compatibility

### PR DESCRIPTION
**Pull request by steffengy**
More work towards  the development branch.

Just merge it after about a week when there are several commits piled up,
so i don't have to create loads of PRs

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Thanks. I'm wondering if we should freeze master branch

**Comment by steffengy** [comment]
@andresgutierrez 
That would atleast reduce the amount of possible merge conflicts, right?

**Comment by ovr** [comment]
It's not needed to freeze master,
For example I can merge master to develop....

**Comment by ovr** [comment]
@andresgutierrez 
Maybe it's time to give write access to @steffengy ?
He can works in `development` branch

**Comment by sergeyklay** [comment]
@ovr +1

**Comment by steffengy** [comment]
@ovr
Of course it's not needed and works without, but the main reasons I think would be to
- keep master stable
- reduce the amount of merges, by introducing all changes in development (insteadof master)
  and then merging one time, once it's deemed stable

I also wouldn't mind write access, but that is also no requirement :)

**Comment by ovr** [comment]
@steffengy 
Write access is needed
You can push PHP 7 changes directly to `development branch`

**Comment by steffengy** [comment]
@ovr 
I agree that if I had those rights, it would make some stuff much easier.
But until then I guess I'll have to create some PRs regularily.

**Pull request merged**
