### PR TITLE
Try to fix #815 issue - replace uint32_t

### LINKED ISSUE #815: compile-errors ??? BUG?
The following error occurred in the `zephir build` implementation, I think it is Bug.
```shell
lll.c
array.c
backtrace.c
concat.c
debug.c
exception.c
exit.c
fcall.c
file.c
E:\Projects\lll\ext\kernel\file.c(155) : warning C4018: “<”: 有符号/无符号不匹配
E:\Projects\lll\ext\kernel\file.c(238) : warning C4018: “>”: 有符号/无符号不匹配
E:\Projects\lll\ext\kernel\file.c(248) : warning C4018: “<”: 有符号/无符号不匹配
filter.c
E:\Projects\lll\ext\kernel\filter.c(57) : warning C4018: “<”: 有符号/无符号不匹配
E:\Projects\lll\ext\kernel\filter.c(98) : warning C4018: “<”: 有符号/无符号不匹配
E:\Projects\lll\ext\kernel\filter.c(131) : warning C4018: “<”: 有符号/无符号不匹配
E:\Projects\lll\ext\kernel\filter.c(235) : warning C4018: “<”: 有符号/无符号不匹配
hash.c
iterator.c
main.c
memory.c
object.c
E:\Projects\lll\ext\kernel\object.c(115) : error C2275: “uint32_t”: 将此类型用作表达式非法
        D:\Server\PHP\php-5.6.4-devel-VC11-x86/include\win32/php_stdint.h(93) : 参见“uint32_t”的声明
E:\Projects\lll\ext\kernel\object.c(115) : error C2146: 语法错误: 缺少“;”(在标识符“i”的前面)
E:\Projects\lll\ext\kernel\object.c(115) : error C2065: “i”: 未声明的标识符
E:\Projects\lll\ext\kernel\object.c(117) : error C2065: “i”: 未声明的标识符
E:\Projects\lll\ext\kernel\object.c(117) : warning C4018: “<”: 有符号/无符号不匹配
E:\Projects\lll\ext\kernel\object.c(118) : error C2065: “i”: 未声明的标识符
```
D:\Server\zephir\ext\kernel\object.c

D:\Server\PHP\php-5.6.4-devel-VC11-x86/include\win32/php_stdint.h(93) 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9545905-compile-errors-bug?utm_campaign=plugin&utm_content=tracker%2F280146&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F280146&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ovr**
cC @xutongle

### CODE REVIEW

**Comment by ovr** [comment]
@xutongle

Is it work for you?

**Comment by xutongle** [comment]
@ovr I was testing

**Comment by xutongle** [comment]
@ovr  
```shell
object.c
E:\Projects\leaps\ext\kernel\object.c(116) : error C2143: 语法错误 : 缺少“;”(在“类型”的前面)
E:\Projects\leaps\ext\kernel\object.c(118) : error C2065: “i”: 未声明的标识符
E:\Projects\leaps\ext\kernel\object.c(118) : warning C4018: “<”: 有符号/无符号不匹配
E:\Projects\leaps\ext\kernel\object.c(119) : error C2065: “i”: 未声明的标识符
```

**Comment by ovr** [comment]
Pull it please again

**Comment by xutongle** [comment]
@ovr The error message is that syntax error
I checked the grammar, sure no mistake. I change the variable declaration position again test!

**Comment by xutongle** [comment]
@ovr Declare a variable in the beginning can be compiled through, thank you!

**Pull request merged**
