### PR TITLE
Allow to append custom C classes to extension

### PR DESCRIPTION
**Pull request by baszczewski**
Allow to append custom C classes to extension. Example configuration:

    "extra-classes": {
        "iterator": {
            "source": "own/test/iterator.c",
            "header": "own/test/iterator.h",
            "entry": "own_test_iterator_ce",
            "init": "Own_Test_Iterator"
        }
    }

Is is really important when zephir functionality is not enough.

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please use fix the PSR2 style? https://travis-ci.org/phalcon/zephir/jobs/65245051#L2116

**Comment by baszczewski** [comment]
@ovr @andresgutierrez 
I will be grateful for review.

**Comment by ovr** [comment]
@baszczewski 
https://travis-ci.org/phalcon/zephir/jobs/65291681#L2132

**Comment by baszczewski** [comment]
@ovr ping

**Comment by steffengy** [comment]
I think you should rebase & squash the commits.
Also maybe the commit message should have a short summary in the title
(first 75 characters) of the changes insteadof a generic "Update Compiler.php".

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
