### PR TITLE
Initial support for PHP7

### PR DESCRIPTION
**Pull request by steffengy**
This PR provides only an "intermediate refactoring" of the current source code,
which is not the abstract state zephir would need to support PHP code generation,
with total separation of backends.

This PR does only aim to provide PHP7 compatibility and therefor required
some refactoring, which was done in a limited extent.

Stuff which would have to be done for that:
-
- Move the operator/statement/optimizer **logic that's depending on the backend** to 
classes of the backend (which currently partly is just in-place in the old files with conditionals)<br/>
So you would have a class providing the **general implementation**, which is **shared** between backends (common code for validating parameters, checking input, ...)
<br/>and a version per backend which handles **code generation** (and temp variable usage, ...)

This PR
====
- provides initial support for PHP7 (ZE3) Extensions (compiler and kernel support)<br/>
(testcases pass, **except preg-match**, requires proper reference support in zephir)

Todos
===
- [x] compare generated sources for ZE2
    - generated code for zephir tests seems to match
- [ ] complete some backend definitions (in BaseBackend)
- [ ] general cleanup, eventually more performance tweaks/documentation

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Huge thanks!

**Comment by flip111** [comment]
:+1: Awesome, eager for the zephir-parser.exe :)

**Comment by steffengy** [comment]
@flip111 It's the same as before

**Comment by flip111** [comment]
You mean the binary file has been updated in the development branch? I will check it, thank you.

**Comment by steffengy** [comment]
No but you can grab the most current one from appveyor and I mean it hasn't changed for PHP7

**Comment by flip111** [comment]
These are the errors i was talking about
```
Generating Code...
        "cl.exe" /D _USRDLL /D PHP7DLLTS_EXPORTS /D PHP_EXPORTS /D LIBZEND_EXPORTS /D TSRM_EXPORTS /D SAPI_EXPORTS /D WINVER=0x0600 /D COMPILE_DL_FTP /D COMPILE
_DL_OPCACHE -Ipecl\zep\utils\ext /D ZEPHIR_RELEASE /nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3
/FD /wd4996 /D_USE_32BIT_TIME_T=1 /RTC1 /MP /LDd /MDd /W3 /Gm /Od /D _DEBUG /D ZEND_DEBUG=1 /ZI /D ZTS=1 /I "D:\dev\php7\bin\phpdev\vc14\x86\no\include" /D FD_S
ETSIZE=256 /FoD:\dev\php7\bin\phpdev\vc14\x86\Debug_TS\pecl\zep\utils\ext\ /FpD:\dev\php7\bin\phpdev\vc14\x86\Debug_TS\pecl\zep\utils\ext\ /FRD:\dev\php7\bin\ph
pdev\vc14\x86\Debug_TS\pecl\zep\utils\ext\ /FdD:\dev\php7\bin\phpdev\vc14\x86\Debug_TS\pecl\zep\utils\ext\ /c pecl\zep\utils\ext\utils.c
utils.c
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\main.h(90): warning C4013: 'Z_REFCOUNT_PP' undefined; assuming extern returning int
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\main.h(90): warning C4013: 'Z_ISREF_PP' undefined; assuming extern returning int
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\main.h(93): warning C4013: 'ALLOC_ZVAL' undefined; assuming extern returning int
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\main.h(94): warning C4013: 'Z_UNSET_ISREF_P' undefined; assuming extern returning int
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(748): warning C4047: 'function': 'zval *' differs in levels of indirection from 'zval **'
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(748): warning C4024: '_zval_ptr_dtor': different types for formal and actual parameter 1
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(756): warning C4013: 'ALLOC_INIT_ZVAL' undefined; assuming extern returning int
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(763): warning C4013: 'COPY_PZVAL_TO_ZVAL' undefined; assuming extern returning int
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(785): warning C4047: 'function': 'zval *' differs in levels of indirection from 'zval **'
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(785): warning C4024: '_zval_ptr_dtor': different types for formal and actual parameter 1
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(826): warning C4047: 'function': 'zval *' differs in levels of indirection from 'zval **'
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.h(826): warning C4024: '_zval_ptr_dtor': different types for formal and actual parameter 1
d:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\utils.c(103): error C2065: 'tsrm_ls': undeclared identifier
NMAKE : fatal error U1077: '"D:\dev\Microsoft Visual Studio 14.0\VC\BIN\cl.exe"' : return code '0x2'
Stop.
```

I have been able to build an hello world extension (without zephir) so i'm pretty confident my toolchain is setup right ... though i might have made some mistakes on the zephir part.

**Comment by steffengy** [comment]
@flip111 
seems like you are compiling for PHP5 and trying to compile that with PHP7, which cant work

**Comment by flip111** [comment]
How can i compile for PHP7? is there a switch on `zephir` to turn it on? PHP sources retrieved as such
`git clone -b PHP-7.0.0 --single-branch https://github.com/php/php-src.git . ` (so no PHP5 sources should be present AFAIK)

**Comment by steffengy** [comment]
The problem is that if you do not specify a target version,
the target version is assumed to be your PHP version (the version of the PHP running your compiler).
You still can use a PHP5 version for compilation 
if you explicitly specify ``zephir build --backend ZendEngine3``

**Comment by flip111** [comment]
@steffengy thank you very much. Great work. The zephir `hello world` demo works now!

FYI i think on windows you can not issue `zephir build` directly (it will give some errors). I found that the build process on windows is different than on linux (where you can use phpize). My zephir build commands:
```
mkdir zep
cd zep
zephir init utils --backend ZendEngine3
cd utils
cp ../../greeting.zep utils\greeting.zep
zephir generate --backend ZendEngine3
```

And then to generate core + extensions again:
```
CD ..
CD pecl\zep\utils\utils
zephir generate --backend ZendEngine3
CD ../../../../
nmake clean
CALL buildconf --force --add-modules-dir=%CD%\pecl\zep\utils
CALL configure --enable-debug --enable-phpdbg --enable-utils=shared
nmake
CD Debug_TS
(echo extension_dir = %CD% && echo extension = php_utils.dll) > php.ini
echo.
echo.
php -r "echo Utils\Greeting::say();"
```
the zephir extension will be compiled along with it.

It's very frustrating (build times) not being able to compile a single extension on windows. Perhaps i could just call `cl.exe` myself because there doesn't seem to be a script for this (but this is a php issue, not zephir)

**Comment by steffengy** [comment]
On windows you can also use phpize,
 thats what zephir build does, see Windows.md even though it might be outdated for now.

**Comment by flip111** [comment]
@steffengy that's good to know. Would you know how to use phpize on windows? Some sources claim it's not possible

[The windows version of phpize seems to be broken](http://www.sitepoint.com/compiling-php-from-source-on-windows/) (2012)
[On Windows, you don't call phpize but instead you call buildconf.bat.](http://blog.benoitblanchon.fr/build-php-extension-on-windows/) (2015)

Myself if i run `phpize.bat` i get:
```
Input Error: Can not find script file "D:\dev\php7\bin\phpdev\vc14\x86\win32\build\script\phpize.js".
Now run 'configure --help'
```
Because of https://github.com/php/php-src/blob/PHP-7.0.0/win32/build/phpize.bat#L2-L3 where it sets the current directory and then the script directory is not available in the current directory.

Is this a candidate for the php bugtracker, or am i doing wrong here and it should be possible like you say?

**Comment by steffengy** [comment]
@flip111 
It's just not documented how it works, but it does work.
You need to build a devpack first though and use the built phpize

**Comment by flip111** [comment]
@steffengy devpack? Are you refering to [these steps](https://wiki.php.net/internals/windows/stepbystepbuild#setup_the_build_directory)? `bin\phpsdk_buildtree.bat phpdev` ?? I have done this..
I noticed documentation is missing, i'm trying to write down the full procedure somewhere, but i got stuck at phpize...

**Comment by steffengy** [comment]
No I mean you need a devel-pack which contains a working version of phpize.
You get this by building a release archive ( ``nmake snap`` or simply ``nmake build-devel`` ) and then use ``<Build_Dir>\Release\php-7.0.0beta3-devel-VC14-x86\phpize.bat`` as phpize

**Comment by flip111** [comment]
Hi, thanks for your support again. I've been able to build phpize on windows with the instructions you gave me. Though it doesn't work yet (the makefile is incomplete) ... i'm still working on tracking down the problem with phpize. As for zephir i believe the `build` command in not supported on windows because of

https://github.com/phalcon/zephir/blob/master/Library/Compiler.php#L1178

and

https://github.com/phalcon/zephir/blob/master/Library/Compiler.php#L1099

The `WINDOWS.md` file seems to be outdated indeed ...

The full output:
```
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils>zephir build
Copying new kernel files...
The system cannot find the path specified.
Preparing for PHP compilation...
The system cannot find the path specified.
Preparing configuration file...
Compiling...
Installation is not implemented for windows yet! Aborting!
```

Also when i didn't launch from the compiler environment but a regular prompt:
```
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils>zephir build
Copying new kernel files...
The system cannot find the path specified.
Preparing for PHP compilation...
The system cannot find the path specified.
Preparing configuration file...
ERROR: Compiler not found
Compiling...
Installation is not implemented for windows yet! Aborting!
```

At least there seems to be missing some logic there with messages like `Compiler not found` --> `Compiling...`

Perhaps worth to open an issue for this?

**Comment by steffengy** [comment]
@flip111 
zephir install is not supported but zephir compile is, there's a difference.
It also cannot work from a regular prompt, since a compiler cannot be found like that.
the first output seems correct, are you sure that the build hasn't worked - since for me anything seems fine, since it passed compilation and reached installation and aborted there since that isn't implemented for windows. 
Was no .dll file created or how do you come to the conclusion that the build for your full output failed?

**Comment by flip111** [comment]
@steffengy
I think i was a bit too quick to come to the conclusion that the output failed. After i tried in the right environment (with compiler setup) i didn't check the files anymore. Anyway .. there seem to have been some files created:
```
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\utils.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\vc140.idb
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\resp\UTILS_GLOBAL_OBJS.txt
```
Some questions about this:
1. How can i build the DLL (extension as shared library). I noticed the `config.w32` file which gets generated has `EXTENSION("utils", "utils.c", null, "-I"+configure_module_dirname);` with 3rd parameter to `null` (should be `true` for shared library)
2. Why are the path names so incredibly long? Seems to have taken a wrong basepath?
3. Why am i getting those `The system cannot find the path specified.` messages, and which files are they referring to?

**Comment by steffengy** [comment]
1. shouldn't matter since it isn't compiling PHP
2. probably absolute paths
3. cannot say

does D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\ contain a .dll file?
Have you checked the compile_errors / compile output file?

**Comment by flip111** [comment]
about 2. and 3. i will try to find this later ...

about 1. this is still a problem ... yes i made another mistake by forgetting to set the backend ... (checking the compiler logs was a good idea) ... though still no DLL file. `php_utils.lib` seems like a static binary.

File present:
```
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\php_utils.dll.manifest
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\php_utils.dll.res
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\php_utils.exp
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\php_utils.lib
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\utils.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\utils.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\vc140.idb
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\array.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\array.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\backtrace.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\backtrace.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\concat.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\concat.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\debug.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\debug.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\exception.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\exception.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\exit.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\exit.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\fcall.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\file.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\file.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\filter.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\filter.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\hash.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\hash.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\iterator.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\iterator.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\main.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\main.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\math.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\math.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\memory.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\memory.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\object.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\object.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\operators.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\operators.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\require.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\require.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\string.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\string.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\time.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\time.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\variables.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\variables.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\vc140.idb
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\extended\array.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\extended\array.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\extended\fcall.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\extended\fcall.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\kernel\extended\vc140.idb
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\utils\greeting.zep.obj
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\utils\greeting.zep.sbr
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\utils\vc140.idb
D:\dev\php7\bin\phpdev\vc14\x86\pecl\zep\utils\ext\Release_TS\resp\UTILS_GLOBAL_OBJS.txt
```

**Comment by steffengy** [comment]
Just tested it locally, for me it works perfectly generating a dll file, so there's likely something
failing during compilation on your end.
(.lib in that case is an object file library and no statically linked binary)

**Comment by flip111** [comment]
yes there is a problem with the linker ... i edited my previous comment and put the logs at the bottom

**Comment by steffengy** [comment]
You are causing total chaos in your build tree.
It seems like you have used a Debug devpack to build a release extension!? 
``Debug_TS\php-7.0.0beta3-devel-VC14-x86``
Probably you have built with --enable-debug before you used nmake build-devel.

**Comment by flip111** [comment]
@steffengy yes you are right ... i would like to put _everything_ on Debug until code is ready for Release. (I might need debug symbols for debugging)

**Comment by steffengy** [comment]
@flip111 
You could also have debug symbols with release builds but thats another story.
(If you wanted to put zephir into debug mode, which is rarely necessary to track an issue down,
that would also be a bit harder on windows.)
So the problem here is that when windows support was added, the builddev option
hasn't existed yet. 
(So there is basically no comfortable way to build a development extension yet)
So you would probably have to do the build steps manually.
``cd extFolder\ext && configure --enable-extname --enable-debug && nmake``
should cover it

**Pull request merged**
